apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ml-hyper
spec:
  replicas: 15
  serviceName: ml-hyper
  selector:
    matchLabels:
      app: ml-hyper
  template:
    metadata:
      labels:
        app: ml-hyper
    spec:
      containers:
        - name: ml-hyper
          image: ghcr.io/2425-4bhitm-itp/ml:latest
          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: POD_INDEX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command:
            - /bin/sh
            - -c
            - |
              export POD_INDEX=$(echo "${POD_NAME}" | awk -F'-' '{print $NF}')
              exec python -m test.test

          volumeMounts:
            - name: song-volume
              mountPath: /app/song-storage
            - name: model-volume
              mountPath: /opt/model
            - name: env-volume
              mountPath: /env
      volumes:
        - name: song-volume
          persistentVolumeClaim:
            claimName: song-volume-claim
        - name: model-volume
          persistentVolumeClaim:
            claimName: model-volume-claim
        - name: env-volume
          persistentVolumeClaim:
            claimName: env-volume-claim
