apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ml-hyper
spec:
  replicas: 8
  serviceName: ml-hyper
  selector:
    matchLabels:
      app: ml-hyper
  template:
    metadata:
      labels:
        app: ml-hyper
    spec:
      initContainers:
        - name: hyper-env-cleaner
          image: busybox
          command:
            - sh
            - -c
            - |
              rm -rf /env/hyperparam/*
          volumeMounts:
            - name: env-volume
              mountPath: /env
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: cpu-extensions
                  operator: In
                  values:
                    - avx

      containers:
        - name: ml-hyper
          image: ghcr.io/2425-4bhitm-itp/ml:latest
          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command:
          - /bin/sh
          - -c
          - |
            INDEX=$(echo "${POD_NAME}" | awk -F'-' '{print $NF}')
            export POD_INDEX=$INDEX
            echo "POD_NAME=$POD_NAME POD_INDEX=$POD_INDEX"
            exec python -m test.test
          volumeMounts:
            - name: song-volume
              mountPath: /app/song-storage
            - name: model-volume
              mountPath: /opt/model
            - name: env-volume
              mountPath: /env
      volumes:
        - name: song-volume
          persistentVolumeClaim:
            claimName: song-volume-claim
        - name: model-volume
          persistentVolumeClaim:
            claimName: model-volume-claim
        - name: env-volume
          persistentVolumeClaim:
            claimName: env-volume-claim
