apiVersion: v1
kind: Service
metadata:
  name: ml-api
spec:
  selector:
    app: ml-api
  ports:
    - name: http
      port: 5001
      targetPort: 5001
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ml-api
spec:
  serviceName: ml-api
  replicas: 1
  selector:
    matchLabels:
      app: ml-api
  template:
    metadata:
      labels:
        app: ml-api
    spec:
      containers:
        - name: ml-api
          image: ghcr.io/2425-4bhitm-itp/ml:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          command:
            - python
            - -m
            - app.app_cnn
          volumeMounts:
            - name: song-volume
              mountPath: /app/song-storage
            - name: model-volume
              mountPath: /opt/model
            - name: env-volume
              mountPath: /env
          startupProbe:
            httpGet:
              path: /health
              port: 5001
            failureThreshold: 12
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 30
            periodSeconds: 60
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: cpu-extensions
                  operator: In
                  values:
                    - avx
      volumes:
        - name: song-volume
          persistentVolumeClaim:
            claimName: song-volume-claim
        - name: model-volume
          persistentVolumeClaim:
            claimName: model-volume-claim
        - name: env-volume
          persistentVolumeClaim:
            claimName: env-volume-claim
